GET http://localhost:3000/
####

POST http://localhost:3000/login

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "password":"123456",
    "username":"upppi"
}

###
POST https://localhost:3000/login
Content-Type: application/json

{
    "password":"123456",
    "username":"upppi"
}

###
POST http://localhost:3000/logout
